version: '3.7'
# https://docs.docker.com/compose/compose-file/compose-file-v3/

services:
  hubmap-ubkg-api:
    hostname: hubmap-ubkg-api
    container_name: hubmap-ubkg-api
    # Use the published image from DockerHub instead of local build
    # Exit with an error message containing err if UBKG_API_VERSION is unset or empty in the environment
    image: ubkg-api:${UBKG_API_VERSION:?err}
    # Avoid accidentally creating zombie processes
    init: true
    # Specifying a restart policy to avoid downtime
    restart: always
    environment:
      # UID and GID 1001 to match the hive user by default
      - HOST_GID=${HOST_GID:-1001}
      - HOST_UID=${HOST_UID:-1001}
    networks:
      - gateway_hubmap
    volumes:
      # Persist the logging
      - "./src/log:/usr/src/app/log"
      # Mount the app config to container in order to keep it outside of the image
      - "../src/instance:/usr/src/app/src/instance"

networks:
  gateway_hubmap:
    external: true