version: '3.7'
# https://docs.docker.com/compose/compose-file/compose-file-v3/

services:
  ubkg-api:
    container_name: ubkg-container
    build: ./ubkg-api
    init: true
    restart: always
    environment:
      - HOST_GID=${HOST_GID:-1000}
      - HOST_UID=${HOST_UID:-1000}
    volumes:
      # Persist the logging
      - "../log:/usr/src/app/log"
      # Mount the source code to container
      - "../src:/usr/src/app/src"
      # Mount conf.d on host machine to the nginx conf.d on container
      - "./ubkg-api/nginx/conf.d:/etc/nginx/conf.d"
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - "8080:8080"

volumes:
  ubkg-neo4j-data:

