services:
  
  ubkg-front-end:
    build:
      context: ./ubkg-api
      # Configure Compose for multi-architecture builds.
      # Prerequisite: creating an additional buildx builder by running
      # docker buildx create --use
      # Build tags for both the current version and "latest".
      tags:
        - docker.io/hubmap/ubkg-front-end:${UBKG_API_VERSION:?err}
        - docker.io/hubmap/ubkg-front-end:latest
      x-bake:
        platforms:
          # To do: modify Dockerfile to manage yum filesystem to accommodate multiple builds.
          #- linux/amd64
          - linux/arm64
    # Build the image with name and tag
    # Exit with an error message containing err if unset or empty in the environment
    image: hubmap/ubkg-front-end:${UBKG_API_VERSION:?err}
    volumes:  
      # Mount the VERSION file and BUILD file 
      - "../VERSION:/usr/src/app/VERSION" 
      - "../BUILD:/usr/src/app/BUILD" 
      # Mount the source code to container  
      - "../src:/usr/src/app/src"

